### ISSUE TITLE
can't run on centos7

### ISSUE THREAD

**Issue by njwangwei** [neo-project/neo-cli#108]
error info:
[root@gate1 neo-cli]# dotnet neo-cli.dll

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libleveldb': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Neo.IO.Data.LevelDB.Native.leveldb_options_create()
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Shell.MainService.OnStart(String[] args)
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)
Aborted
------------------
Running transaction
  Installing : leveldb-1.12.0-11.el7.x86_64                                                                                                                             1/1 
  Verifying  : leveldb-1.12.0-11.el7.x86_64                                                                                                                             1/1 

Installed:
  leveldb.x86_64 0:1.12.0-11.el7                                                                                                                                            

Complete!
---------------------
os centos-7,dotnet core 2.1.4

**Comment by njwangwei** [comment]
yum install leveldb-devel
