### ISSUE TITLE
neo-cli-ubuntu.16.04-x64.zip  can not run on ubuntu 16.04, please check this bug , thanks!

### ISSUE THREAD

**Issue by kevingwang** [neo-project/neo-cli#110]
ubuntu@VM-0-2-ubuntu:~$ cd hwapp/
ubuntu@VM-0-2-ubuntu:~/hwapp$ 
ubuntu@VM-0-2-ubuntu:~/hwapp$ dotnet run
Hello World!
ubuntu@VM-0-2-ubuntu:~/hwapp$ 
ubuntu@VM-0-2-ubuntu:~/hwapp$ cd ..
ubuntu@VM-0-2-ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
ubuntu@VM-0-2-ubuntu:~$ 
ubuntu@VM-0-2-ubuntu:~$ cd neo-cli/
ubuntu@VM-0-2-ubuntu:~/neo-cli$ dotnet neo-cli.dll /rpc

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libleveldb': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Neo.IO.Data.LevelDB.Native.leveldb_options_create()
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Shell.MainService.OnStart(String[] args)
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)
Aborted (core dumped)
ubuntu@VM-0-2-ubuntu:~/neo-cli$ dotnet neo-cli.dll

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libleveldb': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Neo.IO.Data.LevelDB.Native.leveldb_options_create()
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Shell.MainService.OnStart(String[] args)
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)
Aborted (core dumped)
ubuntu@VM-0-2-ubuntu:~/neo-cli$ dotnet neo-cli
No executable found matching command "dotnet-neo-cli"
ubuntu@VM-0-2-ubuntu:~/neo-cli$ dotnet neo-cli /rpc
No executable found matching command "dotnet-neo-cli"
ubuntu@VM-0-2-ubuntu:~/neo-cli$

**Comment by kevingwang** [comment]
There is no libleveldb file in your publication package.
