### ISSUE TITLE
Wallet open System.NullReferenceException

### ISSUE THREAD

**Issue by Vurdalacky** [neo-project/neo-cli#111]
Hello

I`m upgrade my neo-cli and resync blockchain. Now i get error when i open my wallet:

NEO-CLI Version: 2.7.1.0

neo> show state
Height: 0/1890585/1917338, Nodes: 1

neo> open wallet wallet.db3
password: ********************
neo> 
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Neo.Wallets.WalletIndexer.ProcessBlock(Block block, HashSet`1 accounts, WriteBatch batch)
   at Neo.Wallets.WalletIndexer.ProcessBlocks()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
Aborted

**Comment by Vurdalacky** [comment]
Try re-download block:

neo> show state
Height: 0/1868974/1943795, Nodes: 1
neo> open wallet wallet.db3
password: 
Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.Persist(Block block)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.PersistBlocks()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
Aborted

**Comment by lock9** [comment]
@Vurdalacky  Hello. Are you still facing problems? If possible, create a wallet using .json instead of db3. Since it is plain text, it is easier to keep and maintain.
If you don't have this problem anymore, maybe you can close this issue?
