### ISSUE TITLE
Exception running on ubuntu 16.04

### ISSUE THREAD

**Issue by juliavi** [neo-project/neo-cli#112]
After installing .NET Core 2, and the dependencies 
`sudo apt-get install libleveldb-dev sqlite3 libsqlite3-dev libunwind8-dev`

Running `dotnet .neo-cli.dll`
Returns this exception 

Unhandled Exception: Neo.IO.Data.LevelDB.LevelDBException: IO error: Chain/LOCK: No such file or directory
   at Neo.IO.Data.LevelDB.NativeHelper.CheckError(IntPtr error)
   at Neo.IO.Data.LevelDB.DB.Open(String name, Options options)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Shell.MainService.OnStart(String[] args)
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)
Aborted (core dumped)

Is this a problem with the .NET version on ubuntu? Should I downgrade to .Net Core 1?

**Comment by jonatanblockchain** [comment]
Try:
`sudo apt-get install libleveldb-dev libleveldb1v5 libicu-dev sqlite3 libsqlite3-dev libunwind8-dev`

Chain folder exists? It's locked?

**Comment by juliavi** [comment]
Found the solution, after noticing that the folder is locked and requires permissions, 
I ran the cli with sudo
`sudo dotnet neo-cli.dll`
