### ISSUE TITLE
unhandled exception when opening neo-cli without administrator right

### ISSUE THREAD

**Issue by kokahunter** [neo-project/neo-cli#119]
Running from SSD (240GB SanDisk Ultra) where writes need administrator permissions. Should this error be handled?

Unhandled Exception: Neo.IO.Data.LevelDB.LevelDBException: IO error: Chain/694554.ldb Append: cannot write
   at Neo.IO.Data.LevelDB.NativeHelper.CheckError(IntPtr error)
   at Neo.IO.Data.LevelDB.DB.Open(String name, Options options)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Shell.MainService.OnStart(String[] args)
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)

![neo_exception_open_readonly](https://user-images.githubusercontent.com/1169933/36871568-f410c95a-1da2-11e8-9e6f-c812a123220f.png)

**Comment by jonatanblockchain** [comment]
Did you try delete the chain folder and start again?
