### ISSUE TITLE
Starting Neo Cli rpc Fails on amazon linux after broken pipe

### ISSUE THREAD

**Issue by sunujacob** [neo-project/neo-cli#120]
I have installed a node on my server and was able to run cli from terminal. Terminal returned broken pipe after no activity for sometime. I tried starting neo cli rpc from another terminal (like I usually do) it fails with below error. 

> Neo.IO.Data.LevelDB.LevelDBException
IO error: lock Chain/LOCK: Resource temporarily unavailable
   at Neo.IO.Data.LevelDB.NativeHelper.CheckError(IntPtr error)
   at Neo.IO.Data.LevelDB.DB.Open(String name, Options options)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Shell.MainService.OnStart(String[] args)
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)

The command I used was `cd /home/ec2-user/neo-cli/  
dotnet neo-cli.dll /rpc
`

How can I solve this error? Please Help!!

**Comment by jonatanblockchain** [comment]
sudo dotnet neo-cli.dll ?

**Comment by AshRolls** [comment]
This error would occur if you try and start a second neo-cli instance running from same Chain folder. Are you sure you are not already running neo-cli on your AWS instance (in a screen or detached terminal?)

**Comment by sunujacob** [comment]
It solved by itself after a few hours.. I don't know what caused it though
