### ISSUE TITLE
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by bizlevel** [neo-project/neo-cli#128]
Hello
I use latest debian 9, and use binary file of dotnetcore and neo.
When i run in command **/opt/dotnet-runtime/dotnet /opt/neo-cli/neo-cli.dll --rpc** all is fine:

```
root@neo:/opt# /opt/dotnet-runtime/dotnet /opt/neo-cli/neo-cli.dll --rpc
NEO-CLI Version: 2.7.3.0
neo> exit
root@neo:/opt#
```
I use my **neo.service**:

```
SyslogIdentifier=neo
User=root
Group=root
WorkingDirectory=/opt/neo-cli/
#PIDFile=/opt/neo-cli/neo.pid
ExecStart=/opt/dotnet-runtime/dotnet /opt/neo-cli/neo-cli.dll --rpc
#KillMode=process
#KillSignal=SIGINT
#Restart=on-failure
#PrivateTmp=true
#TimeoutStopSec=60s
#TimeoutStartSec=10s
#StandardOutput=syslog+console
[Install]
WantedBy=multi-user.target
```

And when i try run it **service neo start** - i got error:
```
Mar 23 14:21:47 neo systemd[1]: Starting neo.service...
Mar 23 14:21:47 neo systemd[1]: Started neo.service.
Mar 23 14:21:49 neo neo[24076]: N
Mar 23 14:21:49 neo neo[24076]: Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
Mar 23 14:21:49 neo neo[24076]: at Neo.Services.ConsoleServiceBase.RunConsole()
Mar 23 14:21:49 neo neo[24076]: at Neo.Services.ConsoleServiceBase.Run(String[] args)
Mar 23 14:21:49 neo neo[24076]: at Neo.Program.Main(String[] args)
Mar 23 14:21:49 neo systemd[1]: neo.service: main process exited, code=killed, status=6/ABRT
Mar 23 14:21:49 neo systemd[1]: Unit neo.service entered failed state.
```

What is wrong? Thanks.

**Comment by bizlevel** [comment]
I Still can't demonize neo-cli, even via @reboot in crontab.
Also not work in background via ./neo-cli &
How to run in daemon mode? and i prefer run it like service, that can start and stop if need it.
Thanks.

**Comment by bizlevel** [comment]
Any user - result the same.

I change in service user and group to neo
Also change owner rights to some dirs, but no lucks

```
root@neo:/opt# service neo start
Job for neo.service failed. See 'systemctl status neo.service' and 'journalctl -xn' for details.
root@neo:/opt# systemctl status neo.service
● neo.service
   Loaded: loaded (/usr/lib/systemd/system/neo.service; enabled)
   Active: failed (Result: signal) since Tue 2018-05-08 15:12:39 UTC; 3s ago
  Process: 734 ExecStart=/opt/neo-cli/neo-cli --rpc (code=killed, signal=ABRT)

May 08 15:12:39 neo neo[734]: N
May 08 15:12:39 neo neo[734]: Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
May 08 15:12:39 neo neo[734]: at Neo.Services.ConsoleServiceBase.RunConsole()
May 08 15:12:39 neo neo[734]: at Neo.Services.ConsoleServiceBase.Run(String[] args)
May 08 15:12:39 neo neo[734]: at Neo.Program.Main(String[] args)
May 08 15:12:39 neo systemd[1]: neo.service: control process exited, code=killed status=6
May 08 15:12:39 neo systemd[1]: Failed to start neo.service.
May 08 15:12:39 neo systemd[1]: Unit neo.service entered failed state.

```

**Comment by zhag** [comment]
Ohhh.. Looks like I found the way to demonize this shit...
You should use supervisord

`[program:neo]
directory=/home/neo/neo-cli
command=/usr/bin/dotnet /home/neo/neo-cli/neo-cli.dll --rpc
stdout_logfile=/var/log/neo.log
autostart=true
autorestart=true
user=neo
stopsignal=KILL
numprocs=1`

Don`t forget to enable supervisor on startup `systemctl enable supervisord`

**Comment by MaxSvargal** [comment]
The same shit in Docker @ Ubuntu 16.04

`Step 18/19 : RUN dotnet neo-cli.dll
 ---> Running in cf922f92453b
NEO-CLI Version: 2.7.6.0

neo>
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Neo.Services.ConsoleServiceBase.RunConsole()
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)
Aborted`

**Comment by bizlevel** [comment]
@zhag Hm, your variants - the same as mine, why mine not work with systemd :(

**Comment by bizlevel** [comment]
@zhag It is not ideal, but your variant is work!

**Comment by SBNBON005** [comment]
I am getting the same thing as @MaxSvargal 

On Docker and ubuntu 17.10

My [Dockerfile](https://github.com/SBNBON005/blockchain-nodes/blob/master/neo/Dockerfile)

```
Step 6/7 : RUN cd neo-cli && dotnet neo-cli.dll --rpc --log
 ---> Running in 05b730d91d11
NEO-CLI Version: 2.7.6.1

neo>
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Neo.Services.ConsoleServiceBase.RunConsole()
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)
Aborted
```

**Comment by shargon** [comment]
If the problem persist, please reopen the issue
