### ISSUE TITLE
help!! An error occurred when creating a private chain （Operation is not valid due to the current state of the object.）

### ISSUE THREAD

**Issue by yujiawei** [neo-project/neo-cli#136]
centos7.4
neo-cli 2.7.4
4 nodes

protocol.json

{
  "ProtocolConfiguration": {
    "Magic": 123054,
    "AddressVersion": 23,
    "StandbyValidators": [
        "0282b8ec9b32f6e077a671c80b05300368f9559ccdf8f209455c3e93f7e72ff6a9",
        "03479359eac2105c955298461d09efebc93b079b7acb0db4c8ee68328834d0faa2",
        "0344e15b60ffe1f0cf6f77c91250ee21040bac9db2c07da7d0570070033d977bd6",
        "03ebcda8a4282993ae05e7a852b6ff153433269d33a5f9db72885ac17253f35307"
    ],
    "SeedList": [
      "192.168.0.184:10333",
      "192.168.0.183:10333",
      "192.168.0.179:10333",
      "192.168.0.180:10333"
    ],
    "SystemFee": {
      "EnrollmentTransaction": 0,
      "IssueTransaction": 0,
      "PublishTransaction": 0,
      "RegisterTransaction": 0
    }
  }
}

----------------------------------------------------------------------
neo> open wallet wallet2.json
password: *******
neo> start consensus
[16:06:44] OnStart
[16:06:44] initialize: height=3501 view=0 index=1 role=Primary
[16:06:44] timeout: height=3501 view=0 state=Primary
[16:06:44] send perpare request: height=3501 view=0
[16:06:47] OnPrepareResponseReceived: height=3501 view=0 index=2
[16:07:14] timeout: height=3501 view=0 state=Primary, RequestSent
[16:07:14] request change view: height=3501 view=0 nv=1 state=Primary, RequestSent, ViewChanging
[16:07:40] OnChangeViewReceived: height=3501 view=0 index=0 nv=1
[16:07:41] OnChangeViewReceived: height=3501 view=0 index=2 nv=2
[16:07:58] OnChangeViewReceived: height=3501 view=0 index=3 nv=1
[16:07:58] initialize: height=3501 view=1 index=1 role=Backup
[16:07:59] OnPrepareRequestReceived: height=3501 view=1 index=0 tx=1
[16:07:59] send perpare response
[16:08:00] OnPrepareResponseReceived: height=3501 view=1 index=2

Unhandled Exception: System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Neo.SmartContract.ContractParametersContext.GetScripts()
   at Neo.Consensus.ConsensusService.CheckSignatures()
   at Neo.Consensus.ConsensusService.LocalNode_InventoryReceived(Object sender, IInventory inventory)
   at Neo.Network.LocalNode.Relay(IInventory inventory)
   at Neo.Network.LocalNode.RemoteNode_InventoryReceived(Object sender, IInventory inventory)
   at Neo.Network.RemoteNode.OnInventoryReceived(IInventory inventory)
   at Neo.Network.RemoteNode.<StartProtocol>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
已放弃

**Comment by shargon** [comment]
If the problem persist, please reopen the issue

**Comment by ProDog** [comment]
It caused by the `StandbyValidators` changed.
