### ISSUE TITLE
neo-cli 2.7.5 start error

### ISSUE THREAD

**Issue by metachris** [neo-project/neo-cli#157]
I'm getting the following error when trying to start neo-cli 2.7.5 (things worked in the same setup with 2.7.4 and before):

    # dotnet neo-cli.dll

    Unhandled Exception: System.TypeInitializationException: The type initializer for 'Neo.Settings' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
    Parameter name: format
    at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
    at Neo.PathsSettings..ctor(IConfigurationSection section)
    at Neo.Settings..ctor(IConfigurationSection section)
    at Neo.Settings..cctor()
    --- End of inner exception stack trace ---
    at Neo.Shell.MainService.OnStart(String[] args)
    at Neo.Services.ConsoleServiceBase.Run(String[] args)
    at Neo.Program.Main(String[] args)
    Aborted (core dumped)

**Comment by ryanfalzon** [comment]
Having the same issue. How was this resolved, please?
