### ISSUE TITLE
[testnet] Exception: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by wturyn-cf** [neo-project/neo-cli#185]
Below is a copy from neo-cli console. I've included last persisted block and following events. 
Neo-cli is configured for testnet.

```
[13:49:54] persist block: 0x63ed4ac6cd4346438dfeadfe42c0db5b3031bd59c1174c70db8cfbe80988a6b6
[13:50:10] OnPrepareRequestReceived: height=1563869 view=0 index=6 tx=28
[13:50:12] OnPrepareResponseReceived: height=1563869 view=0 index=3
[13:50:13] OnChangeViewReceived: height=1563869 view=0 index=0 nv=1
[13:50:15] OnChangeViewReceived: height=1563869 view=0 index=1 nv=1
[13:50:16] OnChangeViewReceived: height=1563869 view=0 index=5 nv=1
[13:50:16] OnChangeViewReceived: height=1563869 view=0 index=4 nv=1
[13:50:21] OnPrepareResponseReceived: height=1563869 view=0 index=2
[13:50:23] OnChangeViewReceived: height=1563869 view=0 index=2 nv=1

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Neo.Consensus.ConsensusContext.ChangeView(Byte view_number)
   at Neo.Consensus.ConsensusService.InitializeConsensus(Byte view_number)
   at Neo.Consensus.ConsensusService.LocalNode_InventoryReceived(Object sender, IInventory inventory)
   at Neo.Network.LocalNode.Relay(IInventory inventory)
   at Neo.Network.LocalNode.RemoteNode_InventoryReceived(Object sender, IInventory inventory)
   at Neo.Network.RemoteNode.OnInventoryReceived(IInventory inventory)
   at Neo.Network.RemoteNode.StartProtocol()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted (core dumped)

```

**Comment by erikzhang** [comment]
Fixed in 35ff9a68010bdddc160840f222df13c3c46290f6
