### ISSUE TITLE
How to Convert Interlinked two .class java classes to .avm ?

### ISSUE THREAD

**Issue by SabarishT** [neo-project/neo-cli#193]
**I am getting this error**
> ConvertError:System.Exception: new not supported type.com.sample.main.test.CardInfo
   at Neo.Compiler.JVM.ModuleConverter._ConvertNew(JavaMethod method, OpCode src, NeoMethod to)
   at Neo.Compiler.JVM.ModuleConverter.ConvertCode(JavaMethod method, OpCode src, NeoMethod to)
   at Neo.Compiler.JVM.ModuleConverter.ConvertMethod(JavaMethod from, NeoMethod to)
   at Neo.Compiler.JVM.ModuleConverter.Convert(JavaModule _in)
   at Neo.Compiler.Program.Main(String[] args)

**Comment by superboyiii** [comment]
Let your class file without package and try again. Like this.
![image](https://user-images.githubusercontent.com/38493437/42554531-d56e4874-8517-11e8-8366-8d1ea9a97876.png)

**Comment by superboyiii** [comment]
@SabarishT

**Comment by SabarishT** [comment]
@superboyiii I have tried in default package also. Please find Below 
![test1](https://user-images.githubusercontent.com/29983995/42563426-d6e8c87e-851b-11e8-9216-1f95a3b0aceb.PNG)

Here I am trying to convert ICOTemplate.class to .avm. I am getting same error. TempleToken.java is called(interlinked) in ICOTemplate.java

![test2](https://user-images.githubusercontent.com/29983995/42563497-09165f28-851c-11e8-8fb4-7fbe4fdd9eab.PNG)

Kindly need help in this issue.

**Comment by lock9** [comment]
Hello @SabarishT, 
Are you still having problems?

**Comment by lock9** [comment]
Hello,
I'm closing this due to inactivity.
