### ISSUE TITLE
System.IO.IOException: No space left on device

### ISSUE THREAD

**Issue by jeff-upbit** [neo-project/neo-cli#207]
My neo-cli got this error from yesterday.

```
Unhandled Exception: System.IO.IOException: No space left on device
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at Neo.Shell.MainService.LevelDBBlockchain_ApplicationExecuted(Object sender, ApplicationExecutedEventArgs e)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.Persist(Block block)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.PersistBlocks()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

What is this error?

**Comment by jeff-upbit** [comment]
There are so many files on ApplicationLog folder.(5000000+)
After deleting it, everything is ok.
