### ISSUE TITLE
我用maven项目导入web3，生成签名的时候signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by fanchi1** [neo-project/neo-cli#229]
Exception in thread "main" java.lang.SecurityException: class "org.bouncycastle.jcajce.provider.digest.BCMessageDigest"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.web3j.abi.FunctionEncoder.buildMethodId(FunctionEncoder.java:88)
	at org.web3j.abi.FunctionEncoder.encode(FunctionEncoder.java:28)
	at walletmanager.ETHTest.tranToken(ETHTest.java:448)
	at walletmanager.ETHTest.main(ETHTest.java:76)

**Comment by fanchi1** [comment]
我想知道是什么原因，找了好久实在找不出原因

**Comment by Tommo-L** [comment]
@fanchi1  亲，你的问题有解决了吗？ 若是已经解决了，可以关闭该issue 吗？
若还没有，可否提供下详细问题情况， web3 这个好像是以太坊的， 我们这边是neow3j

**Comment by lock9** [comment]
Hello @fanchi1, I'm closing this issue due to inactivity.
If you think this was a mistake, please create a new issue.
Thanks.

PS: What is that `walletmanager.ETHTest.main` thing? Are you sure you are running neo code? 😂
