### ISSUE TITLE
start neo-cli v2.9.0 error

### ISSUE THREAD

**Issue by meiyoung** [neo-project/neo-cli#239]
OS: Ubuntu Linux 16.04

```
$ dotnet ./neo-cli.dll /rpc
[ERROR][9/10/2018 11:46:55 AM][Thread 0003][akka://NeoSystem/user/$b] Length cannot be less than zero.
Parameter name: length
Cause: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Neo.Network.UPnP.Discover()
   at Neo.Network.P2P.Peer.OnStart(Int32 port, Int32 ws_port)
   at Neo.Network.P2P.LocalNode.OnReceive(Object message)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][9/10/2018 11:46:55 AM][Thread 0006][akka://NeoSystem/user/$b] Error while creating actor instance of type Neo.Network.P2P.LocalNode with 1 args: (Neo.NeoSystem)
Cause: [akka://NeoSystem/user/$b#516510720]: Akka.Actor.PostRestartException: Exception post restart (System.ArgumentOutOfRangeException) ---> System.TypeLoadException: Error while creating actor instance of type Neo.Network.P2P.LocalNode with 1 args: (Neo.NeoSystem) ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Neo.Network.P2P.LocalNode..ctor(NeoSystem system)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Akka.Actor.Props.ActivatorProducer.Produce()
   at Akka.Actor.Props.NewActor()
   --- End of inner exception stack trace ---
   at Akka.Actor.Props.NewActor()
   at Akka.Actor.ActorCell.CreateNewActorInstance()
   at Akka.Actor.ActorCell.<>c__DisplayClass109_0.<NewActor>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.NewActor()
   at Akka.Actor.ActorCell.FinishRecreate(Exception cause, ActorBase failedActor)
   --- End of inner exception stack trace ---
NEO-CLI Version: 2.9.0.0
```

**Comment by oeohomos** [comment]
I got the same problem on Ubuntu 16.04.

**Comment by belane** [comment]
No problem here on Ubuntu 16.04 fresh install.

I've installed dependencies `sudo apt-get install libleveldb-dev sqlite3 libsqlite3-dev libunwind8-dev` and .NET Core from https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/runtime-2.1.0 and is running fine.

Can you give some more details?, like `dotnet --info` or `dpkg -l dotnet-*`

**Comment by belane** [comment]
I've installed the same dotnet version and it works.
```
> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008673
 Commit:    f5e3ddbe73

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300-rc1-008673/

Host (useful for support):
  Version: 2.1.0-rc1
  Commit:  eb9bc92051

.NET Core SDKs installed:
  2.1.300-rc1-008673 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

> dotnet ./neo-cli.dll /rpc
NEO-CLI Version: 2.9.0.0

neo> show state
```

Have you installed all dependencies ?
`sudo apt-get install libleveldb-dev sqlite3 libsqlite3-dev libunwind8-dev`

Also, can you update to last dotnet? I don't think is the problem but just to discard.

**Comment by shargon** [comment]
If the problem persist, please reopen the issue
