### ISSUE TITLE
节点启动报错

### ISSUE THREAD

**Issue by CRChen** [neo-project/neo-cli#246]
使用./neo-cli --rpc启动节点，报如下错误：
`[ERROR][18/10/19 上午2:52:43][Thread 0007][akka://NeoSystem/user/$b] Length cannot be less than zero.
Parameter name: length
Cause: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Neo.Network.UPnP.Discover()
   at Neo.Network.P2P.Peer.OnStart(Int32 port, Int32 ws_port)
   at Neo.Network.P2P.LocalNode.OnReceive(Object message)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][18/10/19 上午2:52:43][Thread 0003][akka://NeoSystem/user/$b] Error while creating actor instance of type Neo.Network.P2P.LocalNode with 1 args: (Neo.NeoSystem)
Cause: [akka://NeoSystem/user/$b#1186229591]: Akka.Actor.PostRestartException: Exception post restart (System.ArgumentOutOfRangeException) ---> System.TypeLoadException: Error while creating actor instance of type Neo.Network.P2P.LocalNode with 1 args: (Neo.NeoSystem) ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Neo.Network.P2P.LocalNode..ctor(NeoSystem system)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Akka.Actor.Props.ActivatorProducer.Produce()
   at Akka.Actor.Props.NewActor()
   --- End of inner exception stack trace ---
   at Akka.Actor.Props.NewActor()
   at Akka.Actor.ActorCell.CreateNewActorInstance()
   at Akka.Actor.ActorCell.<>c__DisplayClass109_0.<NewActor>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.NewActor()
   at Akka.Actor.ActorCell.FinishRecreate(Exception cause, ActorBase failedActor)
   --- End of inner exception stack trace ---
**`**

这个问题是什么原因造成的，是配置文件哪里需要调整吗？看官网的文档上没有提到这一块

**Comment by Tommo-L** [comment]
亲，问题有解决吗？
若是没有解决，像是网络相关导致的，试试最新版本，看看问题还存在吗。  
若是已经解决了，可以关系下该issue吗

**Comment by lock9** [comment]
Hello,
I'm closing this due to inactivity.
If you think this was a mistake, please recreate your issue.
Thanks.
