### ISSUE TITLE
Unable to load DLL 'libleveldb': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by Dmitry-SigmaSW** [neo-project/neo-cli#276]
Hi. I'm trying to install neo-cli, but I'm getting the error specified in the thread name. I'm using Windows Server 2016 x64 and tools [on the picture](https://b.radikal.ru/b18/1812/95/d005fda1fe2d.png)

The folder structure is [here](https://d.radikal.ru/d25/1812/17/5818689253eb.png)

C:\neo-cli-master\neo-cli\bin\release\netcoreapp2.0\win10-x64\publish>dotnet neo-cli.dll

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libleveldb': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Neo.IO.Data.LevelDB.Native.leveldb_options_create()
   at Neo.Persistence.LevelDB.LevelDBStore..ctor(String path)
   at Neo.Shell.MainService.OnStart(String[] args)
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)

**Comment by Dmitry-SigmaSW** [comment]
I have used latest neo-cli release with already included leveldb.dll and it worked.
