### ISSUE TITLE
Can't run neo-cli from pre-compiled binaries

### ISSUE THREAD

**Issue by Dmitry-SigmaSW** [neo-project/neo-cli#277]
Hi. I can't run neo-cli from pre-compiled binaries (v 2.9.3). I'm using Windows Server 2016 x64. I was managed to run it once, but after Windows reinstall I can't anymore, even though I installed necessary packages. The error was:

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libleveldb': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Neo.IO.Data.LevelDB.Native.leveldb_options_create()
   at Neo.Persistence.LevelDB.LevelDBStore..ctor(String path)
   at Neo.Shell.MainService.OnStart(String[] args)
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)

**Comment by Dmitry-SigmaSW** [comment]
Hmm.. is appears, that the problem was related to .Net Core. Works good with 1.1.0, but with 2.2.0 it crashes.

**Comment by Dmitry-SigmaSW** [comment]
The issue is solved for now
