### ISSUE TITLE
Fails to start when have plugins ApplicationLogs or SimplePolicy

### ISSUE THREAD

**Issue by l-vitall** [neo-project/neo-cli#279]
v2.9.3.0 fails on startup with Unhandled Exception: System.TypeLoadException: Method 'Configure' in type 'Neo.Plugins.LogReader' from assembly 'ApplicationLogs, Version=2.9.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Neo.Plugins.Plugin.LoadPlugins(NeoSystem system)
   at Neo.Shell.MainService.OnStart(String[] args)
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)

**Comment by l-vitall** [comment]
Issue occurs because of different versions of neo-cli and plugins. Using the same version resolves the issue
