### ISSUE TITLE
[2.10.0] gracefully handle bind failure

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-cli#309]
When starting neo-cli while the P2P port is in use by another process you get a nasty error. 
```
Eriks-Air:netcoreapp2.1 erik$ dotnet neo-cli.dll
NEO-CLI Version: 2.9.4.0

neo> [ERROR][03/05/2019 14:32:01][Thread 0003][[akka://NeoSystem/system/IO-TCP/$a#2052391860]] Bind failed for TCP channel on endpoint [0.0.0.0:20333]
Cause: System.Net.Sockets.SocketException (48): Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Akka.IO.TcpListener..ctor(TcpExt tcp, IActorRef bindCommander, Bind bind)

neo> exit
```
I think we can handle this more gracefully, especially because it seems to switch to another port automatically.

**Comment by ixje** [comment]
updated title as it also still applies to 2.10.0

**Comment by shargon** [comment]
I think that we can't assign automatic other port, because the user want this port, but i agree that the error could be handled in a better way
