### ISSUE TITLE
[2.10.0] DeathPactExceptions appear on exit

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-cli#317]
```
neo> exit
[ERROR][03/13/2019 13:51:01][Thread 0014][akka://NeoSystem/system/IO-TCP/$l] Monitored actor [[akka://NeoSystem/user/$b#467617422]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#467617422]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][03/13/2019 13:51:01][Thread 0014][akka://NeoSystem/system/IO-TCP/$m] Monitored actor [[akka://NeoSystem/user/$b#467617422]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#467617422]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
```

Reproduce sequence: 
- start neo-cli
- type `show state`
- press `enter` to exit show state
- type `exit`

**Comment by jsolman** [comment]
Death pact exceptions are currently expected and not an indication of bad behavior. We should add a top level actor or another mechanism to prevent the messages on shutdown since it looks problematic.

**Comment by ixje** [comment]
I agree it's not really high priority. It just looks nasty from a UX perspective. I figured it's worth reporting incase the TODO list dries up 😆

**Comment by apisit** [comment]
I just ran into this while trying to run neo-cli private net with a single-node consensus. however, it's not on exit but after it relays the 1st block


```
[11:43:59.829] OnStart
[11:43:59.908] initialize: height=1 view=0 index=0 role=Primary
[11:43:59.982] timeout: height=1 view=0
[11:43:59.987] send prepare request: height=1 view=0
[11:44:00.059] send commit
[11:44:00.125] relay block: height=1 hash=0x94c1c7b48ed36a0bccb754abc5dd491659653dfcd7650c404ab255a405efafff tx=1
NEO-CLI Version: 2.10.2.0

[11:44:02.487] OnStop
[ERROR][06/13/2019 11:44:02][Thread 0005][akka://NeoSystem/system/IO-TCP/$a] Monitored actor [[akka://NeoSystem/user/$b#1774575105]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#1774575105]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
```

**Comment by vladyslavstartsev** [comment]
```
[ERROR][11/30/2019 13:35:26][Thread 0053][akka://NeoSystem/system/IO-TCP/$c] Monitored actor [[akka://NeoSystem/user/$b#850053861]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#850053861]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][11/30/2019 13:35:26][Thread 0053][akka://NeoSystem/system/IO-TCP/$l] Monitored actor [[akka://NeoSystem/user/$b#850053861]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#850053861]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][11/30/2019 13:35:26][Thread 0053][akka://NeoSystem/system/IO-TCP/$m] Monitored actor [[akka://NeoSystem/user/$b#850053861]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#850053861]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][11/30/2019 13:35:26][Thread 0053][akka://NeoSystem/system/IO-TCP/$j] Monitored actor [[akka://NeoSystem/user/$b#850053861]] terminated
Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#850053861]] terminated
   at Akka.Actor.ActorBase.Unhandled(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
```

getting same  thing right now
