### ISSUE TITLE
Private chain nodes would not do Consensus

### ISSUE THREAD

**Issue by nengine** [neo-project/neo-cli#33]
I setup private chain with four nodes on Ubuntu 14.04 as indicated in http://docs.neo.org/en-us/node/private-chain.html, but I got following error in one of the nodes.  Is there minimum memory requirements to run private chains?  Any help is appreciated. 

```
neo>start consensus
[09:50:47] OnStart
[09:50:47] initialize: height=1 view=0 index=3 role=Backup
[09:51:18] timeout: height=1 view=0 state=Backup
[09:51:18] request change view: height=1 view=0 nv=1 state=Backup, ViewChanging
[09:51:25] OnChangeViewReceived: height=1 view=0 index=0 nv=1
[09:52:18] timeout: height=1 view=0 state=Backup, ViewChanging
[09:52:18] request change view: height=1 view=0 nv=2 state=Backup, ViewChanging
[09:52:25] OnChangeViewReceived: height=1 view=0 index=0 nv=2
[09:54:18] timeout: height=1 view=0 state=Backup, ViewChanging
[09:54:18] request change view: height=1 view=0 nv=3 state=Backup, ViewChanging
[09:54:26] OnChangeViewReceived: height=1 view=0 index=0 nv=3
[09:58:18] timeout: height=1 view=0 state=Backup, ViewChanging
[09:58:18] request change view: height=1 view=0 nv=4 state=Backup, ViewChanging
[09:58:25] OnChangeViewReceived: height=1 view=0 index=0 nv=4
[10:06:18] timeout: height=1 view=0 state=Backup, ViewChanging
[10:06:18] request change view: height=1 view=0 nv=5 state=Backup, ViewChanging
[10:06:21] OnPerpareRequestReceived: height=1 view=0 index=1 tx=1

Unhandled Exception: System.NullReferenceException: Object reference not set to                                                                        an instance of an object.
   at Neo.Consensus.ConsensusService.OnPerpareRequestReceived(ConsensusPayload p                                                                       ayload, PerpareRequest message)
   at Neo.Consensus.ConsensusService.LocalNode_InventoryReceived(Object sender,                                                                        IInventory inventory)
   at Neo.Network.LocalNode.Relay(IInventory inventory)
   at Neo.Network.LocalNode.RemoteNode_InventoryReceived(Object sender, IInvento                                                                       ry inventory)
   at Neo.Network.RemoteNode.OnInventoryReceived(IInventory inventory)
   at Neo.Network.RemoteNode.<StartProtocol>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__                                                                       6_1(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C                                                                       ontextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.                                                                       IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted (core dumped)

```

**Comment by erikzhang** [comment]
The latest version has fixed the bug.
https://github.com/neo-project/neo-cli/releases

**Comment by nengine** [comment]
Hi Thanks a lot,  I am using latest version 2.3.2 and would not get previous errors anymore but nothing seems to be happening with all four nodes.  How long would it take for these nodes to start communicating?

```
neo>start consensus
[15:11:25] OnStart
[15:11:25] initialize: height=1 view=0 index=2 role=Backup
[15:11:53] OnChangeViewReceived: height=1 view=0 index=0 nv=1
[15:11:55] timeout: height=1 view=0 state=Backup
[15:11:55] request change view: height=1 view=0 nv=1 state=Backup, ViewChanging
[15:12:52] OnChangeViewReceived: height=1 view=0 index=0 nv=2
[15:12:55] timeout: height=1 view=0 state=Backup, ViewChanging
[15:12:55] request change view: height=1 view=0 nv=2 state=Backup, ViewChanging
show state
Height: 0/0, Nodes: 1
15:14:52] OnChangeViewReceived: height=1 view=0 index=0 nv=3
[15:14:55] timeout: height=1 view=0 state=Backup, ViewChanging
[15:14:55] request change view: height=1 view=0 nv=3 state=Backup, ViewChanging
```

**Comment by nengine** [comment]
Hi Sorry,  After a while I'm still getting the same errors with version 2.3.2.  I have firewall open for ports 10331:10334.  Any other ports must be opened?

```
neo>start consensus
[11:34:00] OnStart
[11:34:00] initialize: height=1 view=0 index=3 role=Backup
[11:34:31] timeout: height=1 view=0 state=Backup
[11:34:31] request change view: height=1 view=0 nv=1 state=Backup, ViewChanging
[11:35:31] timeout: height=1 view=0 state=Backup, ViewChanging
[11:35:31] request change view: height=1 view=0 nv=2 state=Backup, ViewChanging
[11:35:35] OnChangeViewReceived: height=1 view=1 index=2 nv=2
[11:35:44] OnChangeViewReceived: height=1 view=0 index=0 nv=1
show state
Height: 0/4002, Nodes: 2
show node
::ffff:162.243.8.59 port:54619 listen:10333 [1/2]
::ffff:162.243.192.197 port:43796 listen:0 [2/2]
[11:36:43] OnChangeViewReceived: height=1 view=0 index=0 nv=2
[11:36:43] initialize: height=1 view=2 index=3 role=Primary
[11:36:43] timeout: height=1 view=2 state=Primary
[11:36:43] send perpare request: height=1 view=2

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Neo.Consensus.ConsensusService.OnTimeout(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
Aborted (core dumped)

```

**Comment by erikzhang** [comment]
![image](https://user-images.githubusercontent.com/10204923/30121590-b140aa56-935e-11e7-94dd-70df9192f674.png)
It seems that you have connect to the NEO mainnet or testnet and have got some data from it.
Try to remove `Chain` directory and modify `protocol.json` and change the `Magic` number to create a new network for your private chain.

**Comment by nengine** [comment]
Yes, That was it. Many thanks.  In what situation private chain would be more useful as supposed to using main NEO blockchain?
