### ISSUE TITLE
some  transactions have no invocation data( token transfer info ), how to fix it , resync may be help?

### ISSUE THREAD

**Issue by bitcodernull** [neo-project/neo-cli#343]
some  transactions have no invocation data( token transfer info ), how to fix it , resync may be help?

**Comment by bitcodernull** [comment]
my node have no the data
neoscan have the data
so my node have no the whole data

**Comment by kokahunter** [comment]
@bitcodernull Can you provide more info? 

Which version are you using, which transactions are missing token transfer info, do you have the application logs plugin activated from the beginning of syncing, how do you determine that data is missing in your node (rpc call, results)? Thanks!

**Comment by jsolman** [comment]
There are known issues with the VM in the 2.10.1 release that make it incompatible with the MainNet chain. This should be remedied in 2.10.2. For now you need to use 2.10.0 or build using the neo-vm master-2.x branch and include the changes from this PR: https://github.com/neo-project/neo-vm/pull/131

**Comment by bitcodernull** [comment]
i met the same case today。
vesion：
2.10.0.0

getapplicationlog to get token transfer info

Log：
where can i get the logs  of beginning.
i run the neo using tmux
the command:
dotnet ./neo-cli.dll /rpc --log --record-notifications

**Comment by bitcodernull** [comment]
the error log is is :
[ERROR][4/26/19 2:20:23 PM][Thread 0004][akka://NeoSystem/system/IO-TCP/$h] Transport endpoint is not connected
Cause: System.Net.Sockets.SocketException (107): Transport endpoint is not connected
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.get_RemoteEndPoint()
   at Akka.IO.TcpConnection.CompleteConnect(IActorRef commander, IEnumerable`1 options)
   at Akka.IO.TcpOutgoingConnection.<>c__DisplayClass12_0.<Connecting>b__0(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][4/26/19 2:20:23 PM][Thread 0015][akka://NeoSystem/system/IO-TCP/$h] Restarting not supported for connection actors.
Cause: [akka://NeoSystem/system/IO-TCP/$h#584253031]: Akka.Actor.PostRestartException: Exception post restart (System.Net.Sockets.SocketException) ---> Akka.Pattern.IllegalStateException: Restarting not supported for connection actors.
   at Akka.IO.TcpConnection.PostRestart(Exception reason)
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.FinishRecreate(Exception cause, ActorBase failedActor)
   --- End of inner exception stack trace ---

but a lot of transactions is missed
