### ISSUE TITLE
neo wallet windows 10 installation won't initialize

### ISSUE THREAD

**Issue by jaydeeatechs** [neo-project/neo-cli#35]
Hi, I downloaded the Windows 10 version of the Neo wallet and successfully unzipped it.  However when I launch the application file, a Windows command prompt window appears [neo> ...] and so the client application never starts and I can't begin downloading the blockchain.  When I ran in troubleshooting mode, it gives the below error.  Not sure how to get past this error?
...
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Neo.Settings' threw an exception. ---> System.IO.FileNotFoundException: The configuration file 'config.json' was not found and is not optional.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Neo.Settings..cctor()
   --- End of inner exception stack trace ---
   at Neo.Shell.MainService.OnStart(String[] args)
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)

**Comment by erikzhang** [comment]
What you are using is a CLI wallet. You can download the GUI version from here:
https://github.com/neo-project/neo-gui/releases

**Comment by jaydeeatechs** [comment]
What is the difference between the two?

Sent via mobile
