### ISSUE TITLE
Exception has occurred while trying to open wallet [on master]

### ISSUE THREAD

**Issue by im-kulikov** [neo-project/neo-cli#395]
```
Exception has occurred: CLR/System.Security.Cryptography.CryptographicException
Exception thrown: 'System.Security.Cryptography.CryptographicException' in Neo.dll: 'Error occurred during a cryptographic operation.'
   at Neo.Wallets.NEP6.NEP6Wallet.Unlock(String password)
   at Neo.Shell.MainService.OpenWallet(String path, String password) in /tmp/neo-cli/neo-cli/Shell/MainService.cs:line 1193
```

https://github.com/neo-project/neo-cli/blob/bd472a3527d3a18269300c67785996b22bc343c1/neo-cli/Shell/MainService.cs#L1192-L1194

Steps to reproduce:
```
→ git rev-parse --short HEAD
bd472a3
→ dotnet run -v d --project ./neo-cli
// ...
neo> open wallet /tmp/neo-cli/neo-cli/wallet1.json
password: ***
failed to open file "/tmp/neo-cli/neo-cli/wallet1.json"
```

**Comment by shargon** [comment]
master is under development, so is possible to find errors until release neo 3

**Comment by erikzhang** [comment]
It seems to be a password error. In addition, 2.x wallet can not be used on the master branch. You need to recreate your wallet and import your private key.

**Comment by im-kulikov** [comment]
@erikzhang perhaps there is sense to add command to convert 2.x wallet to 3.x wallet?

**Comment by erikzhang** [comment]
Yes. We will release a migration tool in the future.

**Comment by lock9** [comment]
Hello, everyone.
I'm closing this issue due to inactivity. I also think that "it won't be solved' (will it?)
Like @shargon  mentioned:
> master is under development, so is possible to find errors until release neo 3
If you think this was a mistake, please reopen or create a new issue.
Thanks
