### ISSUE TITLE
Unable to install NEO Client

### ISSUE THREAD

**Issue by HunniBadger** [neo-project/neo-cli#40]
I've done a fresh install of Windows 10 and have tried to install the windows 10 NEO client but I'm getting the following error on install: 

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libleveldb': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Neo.Implementations.Blockchains.LevelDB.Native.leveldb_options_create()
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Shell.MainService.OnStart(String[] args)
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)

Is anyone able to help please?

**Comment by PeterLinX** [comment]
I just tried, everything is fine. Did you download neo-cli-win10-x64.zip? If you did, there should be libleveldb.dll in it.

**Comment by ClaudeSoleil** [comment]
Hello,

je ne suis pas sur Windows, je suis sur Mac OS Sierra version 10.12.5

Je n'arrive pas à mettre en place mon ewallet.

Merci
Claude

2017-09-26 12:10 GMT+02:00 Peter Lin <notifications@github.com>:
