### ISSUE TITLE
Access to the path is denied,System.IO.IOException,Bad file descriptor

### ISSUE THREAD

**Issue by yanpl** [neo-project/neo-cli#441]
I installed all the required components of neo-cli

but when i run ./neo-cli --rpc
Encountered the following error

`
Unhandled Exception: System.UnauthorizedAccessException: Access to the path is denied. ---> System.IO.IOException: Bad file descriptor
  --- End of inner exception stack trace ---
  at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
  at Interop.CheckIo(Int64 result, String path, Boolean isDirectory, Func`2 errorRewriter)
  at System.ConsolePal.Read(SafeFileHandle fd, Byte[] buffer, Int32 offset, Int32 count)
  at System.ConsolePal.UnixConsoleStream.Read(Byte[] buffer, Int32 offset, Int32 count)
  at System.IO.StreamReader.ReadBuffer()
  at System.IO.StreamReader.ReadLine()
  at System.IO.SyncTextReader.ReadLine()
  at System.Console.ReadLine()
  at Neo.Services.ConsoleServiceBase.RunConsole()
  at Neo.Services.ConsoleServiceBase.Run(String[] args)
  at Neo.Program.Main(String[] args)`

Please help me Thank you! ! !

**Comment by shargon** [comment]
how do you execute the neo-cli? in which environment?

**Comment by yanpl** [comment]
The server environment is as follows:
CentOS Linux release 7.3.1611 (Core)
	Linux test 3.10.0-514.21.2.el7.x86_64 #1 SMP Tue Jun 20 12:24:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

The neo-cli version is 2.10.2
Installed the four plugins ApplicationLogs, ImportBlocks, SimplePolicy, RpcWallet, but when I started with **./neo-cli -rpc** I encountered the following error
