### ISSUE TITLE
How to get started? leveldb missing.

### ISSUE THREAD

**Issue by dazinator** [neo-project/neo-cli#467]
I am attempting to run this on windows.

I get:

> dotnet neo-cli.dll

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libleveldb' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Neo.IO.Data.LevelDB.Native.leveldb_options_create()
   at Neo.Persistence.LevelDB.LevelDBStore..ctor(String path)
   at Neo.Shell.MainService.OnStart(String[] args)
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)
PS C:\Users\DarrellTunnell\Downloads\neo-cli-portable\neo-cli>

In the readme it says I need to install leveldb from here: https://github.com/erikzhang/leveldb - but there are no instructions in that leveldb repo about how to install that dependency on windows.

**Comment by superboyiii** [comment]
@dazinator Just build the leveldb project and put leveldb.dll into the path of neo-cli and then retry 
```dotnet neo-cli.dll```.

**Comment by aliusman** [comment]
Replace 
`NeoSystem = new NeoSystem(protocol, Settings.Default.Storage.Engine, string.Format(Settings.Default.Storage.Path, protocol.Network.ToString("X8")));`

with 
`NeoSystem = new NeoSystem(protocol, null, null);`

In MainService.css for CLI
