### ISSUE TITLE
testnet raise exception

### ISSUE THREAD

**Issue by oslivan** [neo-project/neo-cli#55]
My system is centos 7,  after I run `dotnet neo-cli.dll /rpc `, neo-cli will raise a exception, error log is below:
```
Unhandled Exception: System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Neo.VM.RandomAccessStack`1.Peek(Int32 index)
   at Neo.SmartContract.ApplicationEngine.CheckArraySize()
   at Neo.SmartContract.ApplicationEngine.Execute()
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.Persist(Block block)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.PersistBlocks()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
Aborted
```
Now the height is 718486, please help, thanks.

**Comment by erikzhang** [comment]
Which version of NEO-CLI do you use? The latest version is OK: https://github.com/neo-project/neo-cli/releases

**Comment by oslivan** [comment]
```
neo>version
2.1.0.0
neo>
Unhandled Exception: System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Neo.VM.RandomAccessStack`1.Peek(Int32 index)
   at Neo.SmartContract.ApplicationEngine.CheckArraySize()
   at Neo.SmartContract.ApplicationEngine.Execute()
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.Persist(Block block)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.PersistBlocks()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
Aborted
```
I just go into console, and automatically exit at once.

**Comment by oslivan** [comment]
OK, latest version is V2.3, I will upgrate.
