### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by freetim** [neo-project/neo-cli#60]
After sending neo to my own wallet I get the following exception when I open my wallet:

```
Unhandled Exception: System.InvalidOperationException: Failed to compare two elements in the array. ---> System.ArgumentException: At least one object must implement IComparable.
   at System.Collections.Comparer.Compare(Object a, Object b)
   at Microsoft.EntityFrameworkCore.Update.Internal.ModificationCommandComparer.Compare(ModificationCommand x, ModificationCommand y)
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(T[] keys, Int32 lo, Int32 hi, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.<BatchCommands>d__8.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Neo.Implementations.Wallets.EntityFramework.UserWallet.OnProcessNewBlock(Block block, IEnumerable`1 added, IEnumerable`1 changed, IEnumerable`1 deleted)
   at Neo.Wallets.Wallet.ProcessNewBlock(Block block)
   at Neo.Wallets.Wallet.ProcessBlocks()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
Aborted
```

And after this I'm back in the bash and no typing will shown in the bash.

**Comment by freetim** [comment]
`upgrade wallet` helped but the same procedure will cause the same exception again.

**Comment by hahahatrick** [comment]
I'm getting the same error. The error comes when I do open wallet. I tried creating a new wallet and open it does not happen.

Please help.

Thank you.

**Comment by freetim** [comment]
@hahahatrick as I wrote. `upgrade wallet` fixed the broken wallet.

**Comment by hahahatrick** [comment]
@freetim I tried upgrade wallet. This gives me 'error'. 

Also, this happened after I did 'sendtoaddress'.

**Comment by SterL** [comment]
I'm also getting this same error. Someone please help. `upgrade wallet` does not appear to be working. After upgrading wallet, i `rebuild index` and i'm able to unlock my wallet and display balances but when I try to send NEO from this wallet I get the same error and my neo-cli gets killed.

**Comment by cedricfung** [comment]
I'm getting the same error, upgrade wallet wallet.db3 return error
