### ISSUE TITLE
dotnet neo-cli.dll ERROR 

### ISSUE THREAD

**Issue by boyue** [neo-project/neo-cli#98]
Neo CLI v2.6.0

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libleveldb': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Neo.IO.Data.LevelDB.Native.leveldb_options_create()
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Shell.MainService.OnStart(String[] args)
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)
Aborted (core dumped)

When i change neo-cli to lower version ,it get error below:

Neo CLI v2.5.2

dotnet neo-cli.dll
System.IO.FileNotFoundException: Unable to find the specified file.
   at Interop.Sys.GetCwdHelper(Byte* ptr, Int32 bufferSize)
   at Interop.Sys.GetCwd()
   at System.IO.UnixFileSystem.GetCurrentDirectory()
   at System.IO.Directory.GetCurrentDirectory()
   at Microsoft.DotNet.Cli.Utils.CommandResolver.TryResolveCommandSpec(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

Both in Windows10 and Ubuntu 16.04
n you help me?

**Comment by jonatanblockchain** [comment]
Just installed a fresh install of both versions on Windows 10 and works well. Did you installs the required deps for Ubuntu and dotnet 2.0?

![2018-01-22 12_40_36-microsoft edge](https://user-images.githubusercontent.com/29895459/35219117-8e8d15e2-ff71-11e7-8d9b-7b8d0cc4c55f.png)

**Comment by 15174834** [comment]
im centos
same problem

**Comment by juliavi** [comment]
How did you install libleveldb on windows?

**Comment by jonatanblockchain** [comment]
@15174834 
Prerequisites Centos:
sudo yum update
sudo yum install epel-release 
sudo yum install leveldb-devel libunwind libicu -y 
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[packages-microsoft-com-prod]\nname=packages-microsoft-com-prod \nbaseurl=https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/dotnetdev.repo'
sudo yum install dotnet-sdk-2.0.0
export PATH=$PATH:$HOME/dotnet
dotnet --version

@juliavi 
leveldb binary is included on neo-cli windows release.
